image: docker/compose:alpine-1.27.4

services:
  - docker:dind

variables:
  PORT: 5000
  UID_GID: 1000:1000

cache:
  key: ${CI_COMMIT_REF_SLUG} # only apply for current branch
  paths:
    - node_modules/

stages:
  - build
  - linting
  - test
  - release
  - deploy

before_script:
  - docker version
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

.run-on-files:
  only:
    changes:
      - '**/*.{ts,js}'
      - '**/*.json'
      - Dockerfile
      - prod/*
      - .gitlab-ci.yml
      - package.json
      - scripts/*

.qa-phase:
  before_script:
    - docker-compose version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-qa
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-qa $CI_REGISTRY_IMAGE:qa

install_dependencies:
  image: node:14-alpine
  stage: build
  before_script:
    - node -v && yarn -v
  script:
    - yarn --frozen-lockfile

.build:
  stage: build
  extends: .run-on-files

build:
  extends: .build
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - >
      DOCKER_BUILDKIT=1 docker build
      --build-arg BUILDKIT_INLINE_CACHE=1 
      --cache-from $CI_REGISTRY_IMAGE:latest 
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA 
      -f ./prod/Dockerfile 
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

build_test:
  extends: .build
  script:
    - docker pull $CI_REGISTRY_IMAGE:qa || true
    - >
      DOCKER_BUILDKIT=1 docker build 
      --build-arg BUILDKIT_INLINE_CACHE=1 
      --cache-from $CI_REGISTRY_IMAGE:qa 
      -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-qa 
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-qa

.lints:
  stage: linting
  needs: ['build']

linting:
  extends: .lints
  script:
    - echo 'PORT=$PORT\nUID_GID=$UID_GID' >> .env
    - . script/compose-start.sh lint

lint-commit-msg:
  extends: .lints
  image: node:14-alpine
  needs:
    - 'install_dependencies'
  before_script:
    - node -v && yarn -v
  script:
    - echo "$CI_COMMIT_MESSAGE" | npx commitlint

.tests:
  extends: .qa-phase
  stage: test
  needs: ['build']

jest:
  extends: .tests
  script:
    - echo 'PORT=$PORT\nUID_GID=$UID_GID' >> .env
    - . script/compose-start.sh test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    paths:
      - coverage/

.release:
  variables:
    GIT_STRATEGY: none
  stage: release
  needs:
    - 'jest'
    - 'linting'

release-tag:
  extends: .release
  except:
    refs:
      - main
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

release-latest:
  extends: .release
  only:
    refs:
      - main
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

release-qa:
  extends: .release
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-qa
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-qa $CI_REGISTRY_IMAGE:CI_COMMIT_REF_SLUG-qa
    - docker push $CI_REGISTRY_IMAGE:CI_COMMIT_REF_SLUG-qa

pages:
  stage: deploy
  needs:
    - jest
  dependencies:
    - jest
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - main

deploy:
  stage: deploy
  needs:
    - 'release-latest'
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - main
  before_script:
    - apk update && apk add openssh-client bash
  script:
    - eval $(ssh-agent -s)

    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'

    - mkdir -p ~/.ssh

    - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts

    - chmod 644 ~/.ssh/known_hosts

    - >
      ssh $SSH_USER@$SSH_SERVER_IP
      "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
      cd ${PATH_TO_PROJECT};
      docker-compose down;
      docker pull ${CI_REGISTRY_IMAGE}:latest;
      docker-compose up -d;
      docker image prune -f;"
