version: '3.0'
services:
  slearning-api:
    container_name: slearning-service-dev
    user: '$UID_GID'
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - ${PORT}:${PORT}
