version: '3.0'

services:
  slearning-api:
    image: registry.gitlab.com/nomorechokedboy/s-learning:qa
    container_name: slearning-service
    user: '$UID_GID'
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    ports:
      - ${PORT}:${PORT}
