version: '3.0'
services:
  slearning-api:
    container_name: slearning-service-dev
    user: '$UID_GID'
    env_file:
      - .env
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - ${SLEARNING_SERVER_PORT}:${SLEARNING_SERVER_PORT}
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:${SLEARNING_SERVER_PORT}/healthcheck || exit 1
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/hadius/Workspace/Nodejs/slearning-backend/node_modules
