export const {
  SLEARNING_SERVER_PORT: PORT,
  SLEARNING_SERVER_MORGAN: MORGAN,
  SLEARNING_SERVER_SECRET_KEY: SECRET_KEY,
  SLEARNING_SERVER_REFRESH_KEY: REFRESH_KEY,
  SLEARNING_SERVER_DATABASE_URL: DATABASE_URL,
} = process.env;
